name: Lint

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - name: Set up Python 3.8
        uses: actions/setup-python@v1 # https://github.com/actions/setup-python
        with:
          python-version: 3.8
      - name: Linting using Pre-Commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
